// presentation/copy/strings.ts — single source for user-visible strings.
// Every literal a user can read lives here, not in a component.

export const copy = {
  brand: 'Cineteca',
  tagline: 'Discover movies. Build your library.',
  nav: {
    primary: 'Main',
    home: 'Home',
    explore: 'Explore',
    search: 'Search',
    myCineteca: 'My Cineteca',
    myLists: 'My Lists',
    skipToContent: 'Skip to content',
  },
  home: {
    title: 'Trending this week',
    description: 'Movies and series trending right now, straight from the TMDB catalog.',
    empty: 'No trending movies to show right now.',
    exploreCta: 'Explore the full catalog',
    loading: 'Loading trending movies…',
    loadingAria: 'Loading home grid',
  },
  explore: {
    title: 'Explore movies',
    description: 'Filter the TMDB catalog by genre, year, minimum rating, and sort order.',
    filters: {
      title: 'Filters',
      genre: 'Genre',
      year: 'Year',
      minRating: 'Minimum rating',
      minVotes: 'Minimum votes',
      sortBy: 'Sort by',
      clear: 'Clear filters',
      any: 'Any',
    },
    sortOptions: {
      popularityDesc: 'Most popular',
      popularityAsc: 'Least popular',
      releaseDateDesc: 'Newest releases',
      releaseDateAsc: 'Oldest releases',
      ratingDesc: 'Highest rated',
      ratingAsc: 'Lowest rated',
      titleAsc: 'Title (A–Z)',
      titleDesc: 'Title (Z–A)',
    },
    emptyInitial: 'No movies to show yet. Try adjusting your filters.',
    emptyByFilter: 'No movies match these filters.',
    clearFiltersAction: 'Clear filters',
    loadMore: 'Load more',
    loading: 'Loading movies…',
    loadingAria: 'Loading explore grid',
  },
  search: {
    title: 'Search movies',
    description: 'Search the TMDB catalog by title, person, or keyword.',
    placeholder: 'Title, person, or keyword…',
    inputLabel: 'Search query',
    emptyInitial: 'Start typing to search the catalog.',
    tooShort: 'Type at least 2 characters to search.',
    emptyResults: 'No movies match this query.',
    noResultsHint: 'Try a different keyword or check your spelling.',
    loading: 'Searching…',
    loadingAria: 'Searching movies',
    ariaLiveRegion: 'Search results',
  },
  detail: {
    back: 'Back',
    backAria: 'Back to previous page',
    overviewLabel: 'Overview',
    noOverview: 'No synopsis available.',
    overviewEnglishFallback: 'No synopsis in your language. Showing the English version:',
    cast: 'Cast',
    noCast: 'No cast information available.',
    trailers: 'Trailers',
    noTrailers: 'No trailers available.',
    trailerOn: 'Watch on',
    recommendations: 'You might also like',
    noRecommendations: 'No recommendations yet.',
    budget: 'Budget',
    revenue: 'Revenue',
    noData: 'No data',
    runtime: 'Runtime',
    status: 'Status',
    statusReleased: 'Released',
    statusUnreleased: 'Unreleased',
    statusUnknown: 'Unknown',
    releasedOn: (date: string) => `Released on ${date}`,
    expectedOn: (date: string) => `Expected on ${date}`,
    voteCount: (count: string) => `${count} votes`,
    voteCountAbsent: 'No ratings',
    loading: 'Loading movie…',
    loadingAria: 'Loading movie details',
    notFoundTitle: 'Movie not found',
    notFoundBody: 'The movie you are looking for does not exist or was removed from the catalog.',
  },
  movieCard: {
    noPoster: 'No poster',
    noYear: '—',
    noRating: 'No rating',
    unreleased: 'Upcoming',
    accessibleName: (title: string, year: string, ratingLabel: string) =>
      `${title}, ${year}, ${ratingLabel}`,
  },
  library: {
    title: 'My Cineteca',
    description: 'Movies you have saved to watch later.',
    empty: 'Your cineteca is empty.',
    emptyHint: 'Save movies from the detail page to find them here.',
    exploreCta: 'Explore movies',
    loading: 'Loading your cineteca…',
    loadingAria: 'Loading saved movies',
    error: 'We could not load your cineteca.',
    corruptedNotice:
      'Your cineteca was reset because the stored data was unreadable. Re-save the movies you want to keep.',
    saved: 'Saved',
    addToLibrary: 'Save to my cineteca',
    removeFromLibrary: 'Remove from my cineteca',
  },
  lists: {
    title: 'My Lists',
    description: 'Themed collections of movies you curate yourself.',
    empty: 'You have not created any lists yet.',
    emptyHint: 'Build a list from your saved movies to organize your cineteca.',
    createCta: 'Create a list',
    createTitle: 'Create a list',
    createDescription:
      'Group the movies you love into themed lists. You can add movies to a list from any detail page.',
    editTitle: 'Edit list',
    editDescription: 'Rename the list or update its description.',
    createAria: 'List creation form',
    nameLabel: 'List name',
    nameHelp: 'Between 1 and 50 characters.',
    descriptionLabel: 'Description (optional)',
    descriptionHelp: 'Up to 20 characters.',
    submitCreate: 'Create list',
    submitEdit: 'Save changes',
    submitInFlight: 'Saving…',
    submitSuccessCreate: 'List created',
    submitSuccessEdit: 'Changes saved',
    cancel: 'Cancel',
    remove: 'Delete list',
    removeConfirm: 'Delete this list?',
    backToLists: 'Back to my lists',
    loading: 'Loading your lists…',
    loadingAria: 'Loading user lists',
    detailLoadingAria: 'Loading list',
    error: 'We could not load your lists.',
    errorCreate: 'We could not create the list. Try again.',
    corruptedNotice:
      'Your lists were reset because the stored data was unreadable. Re-create the lists you want to keep.',
    moviesCount: (count: number) => (count === 1 ? '1 movie' : `${String(count)} movies`),
    movieIdsCount: (count: number) =>
      count === 1 ? '1 saved movie' : `${String(count)} saved movies`,
    noMoviesInList: 'This list has no movies yet.',
    noMoviesInLibraryHint:
      'Save movies to your cineteca first, then add them to this list from the detail page.',
    movieAlreadyInList: 'Already in this list',
    addMovie: 'Add to list',
    removeMovie: 'Remove from list',
    libraryMoviesHeading: 'Your saved movies',
    notFoundTitle: 'List not found',
    notFoundBody: 'The list you are looking for does not exist or was deleted.',
    listUpdated: (date: string) => `Updated ${date}`,
  },
  notFound: {
    title: 'Page not found',
    description: 'The page you are looking for does not exist or has been moved.',
    homeCta: 'Back to home',
  },
  errors: {
    boundaryTitle: 'Something went wrong',
    boundaryDescription: 'An unexpected error stopped the page. You can try again.',
    retry: 'Try again',
    title: 'Something went wrong',
    description: 'We could not load the movies. Please try again.',
  },
  footer: {
    // Required by TMDB's terms of use. Kept verbatim across languages.
    tmdbAttribution: 'This product uses the API of TMDB but is not endorsed or certified by TMDB.',
    tmdbLinkLabel: 'TMDB attribution',
  },
} as const;
